### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by almarklein** [pygfx/gfxmorph#11]
### Progress

* [x] Primary work was just pushed to `main`.
* [x] Tracker logic to e.g. connect with pygfx geometry in #1
* [x] Some refactoring in #2 and #3
* [x] Started on todo in #4 
* [x] More refactoring in #5, #6, #7, #8    
* [x] Setup an actual morph example in #9 
* [x] Better geodesic distance in #10
* [ ] Refactor example to organize all objects better
* [ ] Smoothing
* [ ] Resampling
* [ ] Morph using mesh slices.
* [ ] Move everything to a final place, like pylinalg, pygfx, keep this repo?

### Possible future work

* Improve geodesic distance measuring by taking curvature into account.
* Improve performance by enabling chunking in gfx `Buffer.update_range`. 
* Keeping track of normals could perhaps be delayed if we don't need it for the viz (i.e. no updating normals during the interaction).
* Better morph control in 3D (more degrees of freedom instead of only in direction of the normal).
